version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
        dependency-type: all
    commit-message:
      prefix: "chore"
      include: "scope"
