name: check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.0.5

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: syphar/restore-virtualenv@v1
      - run: pip install -c requirements.txt '.[lint]'
      - run: |
          black --check --diff src tests
          isort --check --diff src tests
