name: check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.1.0

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - uses: syphar/restore-virtualenv@v1
      - run: pip install -c requirements.txt '.[lint]'
      - run: |
          ruff src tests
          black --check --diff src tests

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - uses: syphar/restore-virtualenv@v1
      - run: pip install -c requirements.txt '.[types]'
      - run: mypy src tests
