name: dependencies

on:
  schedule:
    - cron: "0 9 * * 1-5"
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: dependencies-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if dependencies were modified
        id: changed-files
        uses: tj-actions/changed-files@v26.1
        with:
          files: |
            requirements.txt
            pyproject.toml

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - uses: syphar/restore-virtualenv@v1
      - run: pip install --requirement=requirements.txt '.[dev]'

      # skip some dependencies
      - run: pip uninstall --yes setuptools

      - name: "Vulnerabilities: pip-audit"
        if: ${{ steps.changed-files.outputs.any_modified == 'true' || github.event_name == 'schedule' }}
        uses: pypa/gh-action-pip-audit@v1.0.3
