name: dependencies

on:
  schedule:
    - cron: "0 9 * * 1-5"
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if dependencies were modified
        id: changed-files
        uses: tj-actions/changed-files@v14.3
        with:
          files: |
            requirements.txt
            pyproject.toml

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
      - uses: syphar/restore-virtualenv@v1
      - run: pip install -c requirements.txt '.[security]'

      - name: "Vulnerabilities: pip-audit"
        if: ${{ steps.changed-files.outputs.any_modified == 'true' || github.event_name == 'schedule' }}
        run: pip-audit

      - name: "Vulnerabilities: safety (free db updated once a month)"
        if: ${{ steps.changed-files.outputs.any_modified == 'true' || github.event_name == 'schedule' }}
        run: safety check
